site_name: PMF_toolkits Documentation
site_description: PMF_toolkits A Python tool for PMF data processing
site_author: Dinh Ngoc Thuy Vy
site_url: https://dinhngocthuyvy.github.io/PMF_toolkits
repo_url: https://github.com/dinhngocthuyvy/PMF_toolkits
site_dir: _site

copyright: <p> Copyright &copy; 2023-<script>document.write(new Date().getFullYear())</script> Dinh Ngoc Thuy Vy. All Rights Reserved</p>

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - navigation.tracking
    - toc.follow
    - navigation.expand
    - content.tooltips
    - navigation.footer
  font:
    text: Google Sans
    code: Regular

plugins:
  - search
  - mkdocs-jupyter:
      include_source: false
      execute: false
      include_requirejs: true
      ignore_h1_titles: true
      allow_errors: true
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"
  - mkapi
markdown_extensions:
  - pymdownx.tabbed
  - toc:
      permalink: true
  - footnotes
  - nl2br
  - attr_list
  - md_in_html
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - User Guide: quickstart.md
  - API: 'mkapi/api/src/PMF_toolkits' # this use mkapi-fix 2022
  # - API:  $api/src:PMF_toolkits.*** # use mkapi latest but not sure if it works
  - Example:
    - Single-MultiSite: examples/example.ipynb
    - Validation: examples/validation_example.ipynb
    - Preprocessing: examples/preprocessing_example.ipynb
  - Changelog: changelog.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - assets/js/katex.js

extra_css:
  - assets/css/admonition.css
  - assets/css/admonition.css
  - assets/css/customization.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
